name: Build and Deploy to preview URL

on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build-and-preview:
    name: Build and deploy Preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: cd frontend && yarn && yarn build

      - name: preview
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KALKULIERBAR_8EDA1 }}'
          projectId: kalkulierbar-8eda1
          entryPoint: ./frontend
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
